### ISSUE TITLE
Gstreamer Error

### ISSUE THREAD

**Issue by brendan-Wursta** [google/visionai#9]
Hi All, had the following dockerfile working great for streaming a local file two weeks ago but it isn't working now. Any thoughts?

Dockerfile:
```
FROM gcr.io/visionai-public-images/vaictl

COPY stream1.mp4 .
COPY myCredentials.json .

ENV GOOGLE_APPLICATION_CREDENTIALS=./myCredentials.json

CMD echo "Google Application Credentials are set to: $GOOGLE_APPLICATION_CREDENTIALS"
ENTRYPOINT vaictl -p myProjectName -l us-central1 -c application-cluster-0 --service-endpoint visionai.googleapis.com send video-file to streams myStreamName --file-path stream1.mp4 --loop
```

Running in docker with the following:
```
docker build -t visionai .
docker run -it visionai
```

(also tried above with `docker run --platform linux/amd64 -it visionai` as it sometimes errors out)

**Comment by dchao34** [comment]
Hi!

Do you have any logs or error messages?

Also, do you have the your project id? Is it literally "myProjectName"?

Thanks!
- Daniel

FYI
@yxue

**Comment by dchao34** [comment]
Ah, I observe this problem elsewhere too. Will get back to you.

**Comment by dchao34** [comment]
I believe we found the problem. The fix will land in product some time late next week.

**Comment by brendan-Wursta** [comment]
Hi @dchao34 , any update on this issue?

**Comment by dchao34** [comment]
Hey! I think it should be resolved now. You can try again.

**Comment by brendan-Wursta** [comment]
Working now. Thanks @dchao34, appreciate your help!
